<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->headTitle("{$this->locationName} ({$this->stationCode})")
?>
<div>
    <div class="uk-grid uk-flex-middle" data-uk-grid>
        <div class="uk-width-auto">
            <h1 class="uk-margin-remove">
                <a class="uk-link-reset"
                   href="<?= $this->url('home') ?>">
                    Torrix Trains
                </a>
            </h1>
        </div>
        <?php if (! isset($this->error)) : ?>
            <div class="uk-width-expand">
                <h2 class="uk-margin-remove">
                    <?= $this->locationName ?>
                    <span class="uk-text-small"><?= $this->stationCode ?></span>
                </h2>
            </div>
            <div class="uk-width-auto"></div>
            <div class="uk-width-auto">
                <form class="uk-form uk-margin-remove uk-grid uk-grid-small uk-flex-bottom"
                      data-uk-grid
                      id="searchForm"
                      x-data="{station: '' }"
                      method="post"
                      action="/redirect">
                    <div class="uk-width-auto">
                        <label class="uk-form-label" for="station">Station</label>
                        <div class="uk-form-controls">
                            <input class="uk-input"
                                   list="stations"
                                   id="station"
                                   name="station"
                                   x-model="station"
                                   hx-get="/stations"
                                   hx-target="#stations"
                                   hx-trigger="keyup[checkUserKeydown.call(this, event)] changed delay:25ms">
                            <datalist id="stations"></datalist>
                        </div>
                    </div>
                    <div class="uk-width-auto">
                        <input type="submit" class="uk-button uk-button-primary" value="Go">
                    </div>
                </form>
            </div>
        <?php endif ?>
    </div>

    <?php if (isset($this->error)) : ?>
        <div class="uk-alert uk-alert-danger">
            <?= $this->error ?>
        </div>
        <?php return ?>
    <?php endif ?>

    <script>
        function checkUserKeydown(event) {
            return event instanceof KeyboardEvent
        }
    </script>

    <table class="uk-table uk-table-small uk-table-divider"
           id="departures"
           hx-trigger="every 10s"
           hx-select="#departures"
           hx-disinherit="hx-select"
           hx-get="<?= $this->url('station', ['station' => $this->stationCode]) ?>">
        <thead>
        <tr>
            <!--<th>Debug</th>-->
            <th>Due</th>
            <th>Expected</th>
            <th>P</th>
            <th>Destination</th>
            <th>Service</th>
            <th>Operator</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->trainServices as $departure) : ?>
            <tr class="<?= ($departure->etd !== 'On time') ? 'uk-text-danger' : '' ?>">
                <!--<td><?= json_encode($departure) ?></td>-->
                <td><?= $departure->std ?></td>
                <td><?= $departure->etd ?></td>
                <td><?= $departure?->platform ?></td>
                <td>
                    <a hx-boost="true"
                       href="<?= $this->url('station', [
                            'station' => $departure->destination->location->crs ?? '',
                        ]) ?>">
                        <?= $departure->destination->location->locationName ?>
                    </a>
                </td>
                <td class="uk-text-small">
                    From
                    <a hx-boost="true"
                       href="<?= $this->url('station', [
                        'station' => $departure->origin->location->crs ?? '',
                    ]) ?>">
                        <?= $departure->origin->location->locationName ?>
                    </a>
                </td>
                <td class="operator-<?= $departure->operatorCode ?>">
                    <?= $departure->operator ?>
                </td>
            </tr>
        <?php endforeach ?>
        <?php foreach ($this->busServices as $departure) : ?>
            <tr class="<?= ($departure->etd !== 'On time') ? 'uk-text-danger' : '' ?>">
                <!--<td><?php /*= json_encode($departure) */?></td>-->
                <td><?= $departure->std ?></td>
                <td><?= $departure->etd ?></td>
                <td><?= $departure?->platform ?> (BUS)</td>
                <td>
                    <a hx-boost="true"
                       href="<?= $this->url('station', [
                        'station' => $departure->destination->location->crs ?? '',
                    ]) ?>">
                        <?= $departure->destination->location->locationName ?>
                    </a>
                </td>
                <td class="uk-text-small">
                    From
                    <a hx-boost="true"
                       href="<?= $this->url('station', [
                        'station' => $departure->origin->location->crs ?? '',
                    ]) ?>">
                        <?= $departure->origin->location->locationName ?>
                    </a>
                </td>
                <td class="operator-<?= $departure->operatorCode ?>">
                    <?= $departure->operator ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>

<?php if ($this->messages) : ?>
    <?php foreach ($this->messages as $message) : ?>
        <div class="uk-alert uk-alert-danger">
            <?= is_object($message) ? $message->_ : $message ?>
        </div>
    <?php endforeach ?>
<?php endif ?>

